import { sql } from "drizzle-orm";
import { index, integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const companiesBranches = sqliteTable(
  "companies_branches",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    legalName: text("legal_name").notNull(),
    branchName: text("branch_name").notNull(),
    cnpj: text("cnpj").notNull(),
    state: text("state"),
    city: text("city"),
    fiscalEmail: text("fiscal_email"),
    totvsCode: text("totvs_code"),
    qiveIdentifier: text("qive_identifier"),
    status: text("status").notNull().default("ACTIVE"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [uniqueIndex("companies_branches_cnpj_idx").on(table.cnpj)],
);

export const fiscalDocuments = sqliteTable(
  "fiscal_documents",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    documentType: text("document_type").notNull(),
    qiveId: text("qive_id"),
    accessKey: text("access_key"),
    number: text("number"),
    series: text("series"),
    emissionDate: text("emission_date"),
    emitterName: text("emitter_name"),
    emitterCnpj: text("emitter_cnpj"),
    receiverName: text("receiver_name"),
    receiverCnpj: text("receiver_cnpj"),
    ownerCnpj: text("owner_cnpj"),
    ownerRole: text("owner_role"),
    takerName: text("taker_name"),
    takerCnpj: text("taker_cnpj"),
    carrierName: text("carrier_name"),
    carrierCnpj: text("carrier_cnpj"),
    branchId: integer("branch_id").references(() => companiesBranches.id),
    grossValue: real("gross_value"),
    netValue: real("net_value"),
    freightValue: real("freight_value"),
    weightKg: real("weight_kg"),
    icmsValue: real("icms_value"),
    icmsStValue: real("icms_st_value"),
    ipiValue: real("ipi_value"),
    pisValue: real("pis_value"),
    cofinsValue: real("cofins_value"),
    issValue: real("iss_value"),
    inssRetainedValue: real("inss_retained_value"),
    irrfRetainedValue: real("irrf_retained_value"),
    csllRetainedValue: real("csll_retained_value"),
    pisRetainedValue: real("pis_retained_value"),
    cofinsRetainedValue: real("cofins_retained_value"),
    issRetainedValue: real("iss_retained_value"),
    retainedTotal: real("retained_total"),
    taxTotal: real("tax_total"),
    taxesJson: text("taxes_json"),
    fiscalStatus: text("fiscal_status").notNull().default("RECEIVED"),
    source: text("source").notNull().default("QIVE"),
    originalStorageKey: text("original_storage_key"),
    originalHash: text("original_hash"),
    normalizedJson: text("normalized_json"),
    parserVersion: text("parser_version"),
    totvsStatus: text("totvs_status").notNull().default("PENDING"),
    reconciliationStatus: text("reconciliation_status").notNull().default("NOT_PROCESSED"),
    importedAt: text("imported_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex("fiscal_documents_access_key_idx").on(table.accessKey),
    uniqueIndex("fiscal_documents_hash_idx").on(table.originalHash),
    index("fiscal_documents_type_emission_idx").on(table.documentType, table.emissionDate),
    index("fiscal_documents_owner_role_idx").on(table.ownerRole),
    index("fiscal_documents_branch_idx").on(table.branchId),
    index("fiscal_documents_reconciliation_idx").on(table.reconciliationStatus),
  ],
);

export const totvsImports = sqliteTable(
  "totvs_imports",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    fileName: text("file_name").notNull(),
    storageKey: text("storage_key").notNull(),
    fileHash: text("file_hash").notNull(),
    fileSize: integer("file_size").notNull(),
    status: text("status").notNull().default("IMPORTED"),
    totalRows: integer("total_rows").notNull().default(0),
    acceptedRows: integer("accepted_rows").notNull().default(0),
    rejectedRows: integer("rejected_rows").notNull().default(0),
    columnsJson: text("columns_json").notNull().default("[]"),
    mappingJson: text("mapping_json").notNull().default("{}"),
    importedBy: text("imported_by").notNull(),
    importedAt: text("imported_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [uniqueIndex("totvs_imports_hash_idx").on(table.fileHash)],
);

export const totvsRows = sqliteTable(
  "totvs_rows",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    importId: integer("import_id").notNull().references(() => totvsImports.id),
    rowNumber: integer("row_number").notNull(),
    accessKey: text("access_key"),
    documentNumber: text("document_number"),
    series: text("series"),
    cnpj: text("cnpj"),
    supplierName: text("supplier_name"),
    grossValue: real("gross_value"),
    netValue: real("net_value"),
    emissionDate: text("emission_date"),
    dueDate: text("due_date"),
    invoiceNumber: text("invoice_number"),
    titleNumber: text("title_number"),
    costCenter: text("cost_center"),
    branchCode: text("branch_code"),
    rawJson: text("raw_json").notNull(),
    validationStatus: text("validation_status").notNull().default("VALID"),
    validationMessage: text("validation_message"),
  },
  (table) => [index("totvs_rows_import_idx").on(table.importId)],
);

export const reconciliations = sqliteTable(
  "reconciliations",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    documentId: integer("document_id").references(() => fiscalDocuments.id),
    totvsRowId: integer("totvs_row_id").references(() => totvsRows.id),
    matchType: text("match_type").notNull(),
    confidence: real("confidence").notNull().default(0),
    status: text("status").notNull(),
    fiscalValue: real("fiscal_value"),
    totvsValue: real("totvs_value"),
    differenceValue: real("difference_value"),
    evidenceJson: text("evidence_json").notNull().default("{}"),
    reviewedBy: text("reviewed_by"),
    reviewedAt: text("reviewed_at"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    index("reconciliations_status_idx").on(table.status),
    uniqueIndex("reconciliations_pair_idx").on(table.documentId, table.totvsRowId),
  ],
);

export const userDashboards = sqliteTable(
  "user_dashboards",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    userEmail: text("user_email").notNull(),
    name: text("name").notNull(),
    isDefault: integer("is_default", { mode: "boolean" }).notNull().default(false),
    layoutJson: text("layout_json").notNull().default("[]"),
    globalFiltersJson: text("global_filters_json").notNull().default("{}"),
    version: integer("version").notNull().default(1),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [index("user_dashboards_user_idx").on(table.userEmail)],
);

export const portalUsers = sqliteTable(
  "portal_users",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    name: text("name").notNull(),
    email: text("email").notNull(),
    role: text("role").notNull().default("READER"),
    branchScopeJson: text("branch_scope_json").notNull().default("[\"ALL\"]"),
    status: text("status").notNull().default("ACTIVE"),
    lastAccessAt: text("last_access_at"),
    createdBy: text("created_by").notNull(),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex("portal_users_email_idx").on(table.email),
    index("portal_users_status_idx").on(table.status),
    index("portal_users_role_idx").on(table.role),
  ],
);

export const savedReports = sqliteTable("saved_reports", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  userEmail: text("user_email").notNull(),
  name: text("name").notNull(),
  reportType: text("report_type").notNull(),
  filtersJson: text("filters_json").notNull().default("{}"),
  columnsJson: text("columns_json").notNull().default("[]"),
  sortJson: text("sort_json").notNull().default("{}"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const auditLogs = sqliteTable(
  "audit_logs",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    userEmail: text("user_email").notNull(),
    action: text("action").notNull(),
    entityType: text("entity_type").notNull(),
    entityId: text("entity_id"),
    previousValue: text("previous_value"),
    newValue: text("new_value"),
    reason: text("reason"),
    source: text("source").notNull().default("PORTAL"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [index("audit_logs_created_idx").on(table.createdAt)],
);

export const integrationStates = sqliteTable(
  "integration_states",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    integrationKey: text("integration_key").notNull(),
    status: text("status").notNull().default("NOT_CONFIGURED"),
    lastSyncAt: text("last_sync_at"),
    lastCursor: text("last_cursor"),
    receivedCount: integer("received_count").notNull().default(0),
    errorCount: integer("error_count").notNull().default(0),
    queueCount: integer("queue_count").notNull().default(0),
    averageProcessingMs: integer("average_processing_ms"),
    lastError: text("last_error"),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [uniqueIndex("integration_states_key_idx").on(table.integrationKey)],
);
